2019-03-04 23:34:08,216 ERROR: Exception on /login [GET] [in D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py: 1761]
Traceback (most recent call last):
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\OneDrive\ProjectsPython\flask_test\app\routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\OneDrive\ProjectsPython\flask_test\app\templates\login.html", line 2, in top-level template code
    {% from 'bootstrap/form.html' import render_form %}
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/form.html
2019-03-04 23:34:08,244 ERROR: Exception on /login [GET] [in D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py: 1761]
Traceback (most recent call last):
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\OneDrive\ProjectsPython\flask_test\app\routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\OneDrive\ProjectsPython\flask_test\app\templates\login.html", line 2, in top-level template code
    {% from 'bootstrap/form.html' import render_form %}
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/form.html
2019-03-04 23:34:08,253 ERROR: Exception on /login [GET] [in D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py: 1761]
Traceback (most recent call last):
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\OneDrive\ProjectsPython\flask_test\app\routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\OneDrive\ProjectsPython\flask_test\app\templates\login.html", line 2, in top-level template code
    {% from 'bootstrap/form.html' import render_form %}
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "D:\OneDrive\ProjectsPython\venv\py-flask\lib\site-packages\flask\templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/form.html
